package mage.constants;
public enum PlayerAction {
    PASS_PRIORITY_UNTIL_MY_NEXT_TURN, PASS_PRIORITY_UNTIL_TURN_END_STEP,
    PASS_PRIORITY_UNTIL_NEXT_MAIN_PHASE, PASS_PRIORITY_UNTIL_NEXT_TURN,
    PASS_PRIORITY_UNTIL_NEXT_TURN_SKIP_STACK, PASS_PRIORITY_UNTIL_STACK_RESOLVED,
    PASS_PRIORITY_UNTIL_END_STEP_BEFORE_MY_NEXT_TURN, PASS_PRIORITY_CANCEL_ALL_ACTIONS,
    TRIGGER_AUTO_ORDER_RESET_ALL, ROLLBACK_TURNS, CONCEDE,
    MANA_AUTO_PAYMENT_ON, MANA_AUTO_PAYMENT_OFF,
    MANA_AUTO_PAYMENT_RESTRICTED_ON, MANA_AUTO_PAYMENT_RESTRICTED_OFF,
    USE_FIRST_MANA_ABILITY_ON, USE_FIRST_MANA_ABILITY_OFF,
    RESET_AUTO_SELECT_REPLACEMENT_EFFECTS, REVOKE_PERMISSIONS_TO_SEE_HAND_CARDS,
    REQUEST_PERMISSION_TO_SEE_HAND_CARDS, PERMISSION_REQUESTS_ALLOWED_ON,
    PERMISSION_REQUESTS_ALLOWED_OFF, REQUEST_AUTO_ANSWER_RESET_ALL,
    VIEW_LIMITED_DECK, VIEW_SIDEBOARD, HOLD_PRIORITY, UNHOLD_PRIORITY
}
